# ANN 1 Classification - Customer Churn

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('../Data/Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


## Encoding Castegorical Data

### Label Encoding the "Gender" Column

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### One Hot Encoding the "Geography" Column

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Training Test Split

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

### Adding the Output Layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training Set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100


250/250 [==============================] - 1s 1ms/step - loss: 0.5837 - accuracy: 0.6867
Epoch 2/100
250/250 [==============================] - 0s 990us/step - loss: 0.4674 - accuracy: 0.7975
Epoch 3/100
250/250 [==============================] - 0s 997us/step - loss: 0.4432 - accuracy: 0.8052
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4315 - accuracy: 0.8092
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4238 - accuracy: 0.8164
Epoch 6/100
250/250 [==============================] - 0s 995us/step - loss: 0.4183 - accuracy: 0.8217
Epoch 7/100
250/250 [==============================] - 0s 997us/step - loss: 0.4133 - accuracy: 0.8227
Epoch 8/100
250/250 [==============================] - 0s 983us/step - loss: 0.4086 - accuracy: 0.8269
Epoch 9/100
250/250 [==============================] - 0s 966us/step - loss: 0.4034 - accuracy: 0.8280
Epoch 10/100
250/250 [==============================] - 0s 972us/step - loss:

250/250 [==============================] - 0s 968us/step - loss: 0.3359 - accuracy: 0.8635
Epoch 76/100
250/250 [==============================] - 0s 966us/step - loss: 0.3358 - accuracy: 0.8634
Epoch 77/100
250/250 [==============================] - 0s 966us/step - loss: 0.3359 - accuracy: 0.8637
Epoch 78/100
250/250 [==============================] - 0s 971us/step - loss: 0.3357 - accuracy: 0.8636
Epoch 79/100
250/250 [==============================] - 0s 966us/step - loss: 0.3356 - accuracy: 0.8630
Epoch 80/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3354 - accuracy: 0.8616
Epoch 81/100
250/250 [==============================] - 0s 967us/step - loss: 0.3358 - accuracy: 0.8629
Epoch 82/100
250/250 [==============================] - 0s 967us/step - loss: 0.3355 - accuracy: 0.8631
Epoch 83/100
250/250 [==============================] - 0s 963us/step - loss: 0.3345 - accuracy: 0.8629
Epoch 84/100
250/250 [==============================] - 0s 959us/step - loss: 0

## Part 4 Making Predictions and Evaluating the Model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?


**Solution**

In [19]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 87ms/step
[[False]]


### Predicting Test Set Results

In [20]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 815us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1517   78]
 [ 200  205]]


0.861